### ISSUE TITLE
IOErrors after running a command

### ISSUE THREAD

**Issue by ngo** [x64dbg/mona#6]
I've installed mona.py as per instructions, but had to build x64dbgpy from sources (because snapshot artifacts are not available, see https://github.com/x64dbg/x64dbgpy/issues/35).
Now after every command with mona I get an IOError, e.g

```
import mona
mona.mona('modules')
```
===>
```
[+] Command used:
!mona modules

---------- Mona command started on 2019-07-19 09:04:28 (v2.0, rev 577) ----------
[+] Processing arguments and criteria
    - Pointer access level : X
[+] Generating module info table, hang on...
    - Processing modules
    - Done. Let's rock 'n roll.
-----------------------------------------------------------------------------------------------------------------------------------------
 Module info :
-----------------------------------------------------------------------------------------------------------------------------------------
[+] Command used:
!mona modules

---------- Mona command started on 2019-07-19 09:04:28 (v2.0, rev 577) ----------
[+] Processing arguments and criteria
    - Pointer access level : X
[+] Generating module info table, hang on...
    - Processing modules
    - Done. Let's rock 'n roll.
-----------------------------------------------------------------------------------------------------------------------------------------
 Module info :
-----------------------------------------------------------------------------------------------------------------------------------------
<SNIP>
<b>********************************************************************************</b>
<b>Traceback (most recent call last):</b>
<b>  File "C:\Users\ngo\Desktop\x64dbg\release\x32\plugins\x64dbgpy\mona.py", line 18391, in main</b>
<b>    commands[command].parseProc(opts)</b>
<b>  File "C:\Users\ngo\Desktop\x64dbg\release\x32\plugins\x64dbgpy\mona.py", line 11450, in procShowMODULES</b>
<b>    showModuleTable("",modulestosearch)</b>
<b>  File "C:\Users\ngo\Desktop\x64dbg\release\x32\plugins\x64dbgpy\mona.py", line 5825, in showModuleTable</b>
<b>    dbg.log(tline)</b>
<b>  File "C:\Users\ngo\Desktop\x64dbg\release\x32\plugins\x64dbgpy\x64dbgpylib.py", line 862, in log</b>
<b>    pykd.dprintln(self.toAsciiOnly(message), showdml)</b>
<b>  File "C:\Users\ngo\Desktop\x64dbg\release\x32\plugins\x64dbgpy\pykd.py", line 197, in dprintln</b>
<b>    print str</b>
<b>  File "C:\Users\ngo\Desktop\x64dbg\release\x32\plugins\x64dbgpy\x64dbgpy\hooks.py", line 44, in write</b>
<b>    self.__original_stream.write(text)</b>
<b>IOError: [Errno 9] Bad file descriptor</b>
<b></b>
<b>********************************************************************************</b>
```

Not sure that it is relevant, but
 - I've retargeted  x64dbgpy build into VS2019 on Win10.
 - I also used swig 4.0.0, which dropped the -ouputtuple (see https://github.com/x64dbg/x64dbgpy/issues/36), so I had to delete this option from swig/setup.py

**Comment by ngo** [comment]
Removing the line `self.__original_stream.write(text)` from hooks.py mitigates the issue, but I'm not sure what happens to the original file descriptor.
